/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2016-05-06 01:21:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.admin.process.CL_Applications;
import java.sql.ResultSet;
import com.admin.comman.Global;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("    <head>\r\n");
      out.write("\t\t \r\n");
      out.write("        <title>Dynamic Cloud</title>\r\n");
      out.write("      \r\n");
      out.write("        \r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/style.css\" />\r\n");
      out.write("        \r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"./style.css\" type=\"text/css\" />\r\n");
      out.write("        <script src=\"js/modernizr.custom.63321.js\"></script>\r\n");
      out.write("     \r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t\tbody\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tbackground-image: url('images/3.jpg');\r\n");
      out.write("\t\t\t\tbackground-repeat: repeat-x;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\ta\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tfont-size: 18px;\r\n");
      out.write("\t\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t\t\tcolor: brown;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body >\r\n");
      out.write("     <div id=\"st\">&nbsp;&nbsp;\r\n");
      out.write("\t\r\n");
      out.write("\t");

		ResultSet rs=null;
		rs=CL_Applications.applications();
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"content\">\r\n");
      out.write("\t<div class=\"menu\">\r\n");
      out.write("\t\t<ul class=\"primary-menu\">\r\n");
      out.write("\t\t&nbsp;&nbsp;&nbsp;<li><a class=\"social-item\" href=\"");
      out.print(request.getContextPath() );
      out.write("/index.jsp\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/Home.png\" height=\"60\" width=\"60\"></a><span class=\"social-span\">Home</span></li>\r\n");
      out.write("\t\t");
	while(rs.next())
		{
      out.write("\r\n");
      out.write("\t\t\t\t<li><a class=\"social-item\" href=\"");
      out.print(request.getContextPath() );
      out.write("/GetRequest?appid=");
      out.print(rs.getInt(1));
      out.write("&ip=");
      out.print(request.getRemoteAddr());
      out.write("\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/");
      out.print(rs.getString(4));
      out.write("\" height=\"60\" width=\"60\"></a><span class=\"social-span\">");
      out.print(rs.getString(2));
      out.write("</span></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t");
}
	
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div style=\"position:absolute;top:15px;left:800px\">\r\n");
      out.write("\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/JSP/login.jsp\"><font color=\"#D8D8D8\">Admin Login</font></a>\r\n");
      out.write("\t</div>\t\r\n");
      out.write(" </div>\r\n");
      out.write("   \r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
