/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2015-03-28 12:57:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("<SCRIPT LANGUAGE=\"JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("\r\n");
      out.write("// By PATRICK CLINGER (pat_clinger@hotmail.com)\r\n");
      out.write("// Web Site: http://www.proboards.com/\r\n");
      out.write("// Script featured on JavaScript Kit (http://javascriptkit.com)\r\n");
      out.write("// Over 400+ free scripts: javascriptkit.com<br />\r\n");
      out.write("\r\n");
      out.write("var letters = 'ghijklabvwxyzABCDEFef)_+|<>?:mnQRSTU~!@#$%^VWXYZ`1234567opGHIJKLu./;'+\"'\"+'[]MNOP890-='+'\\\\'+'&*(\"{},cdqrst '+\"\\n\";\r\n");
      out.write("var split = letters.split(\"\");\r\n");
      out.write("var num = '';\r\n");
      out.write("var c = '';\r\n");
      out.write("var encrypted = '';\r\n");
      out.write("function encrypt(it)\r\n");
      out.write("{\t \r\n");
      out.write("\tvar b = '0';\r\n");
      out.write("\tvar chars = it.split(\"\");\r\n");
      out.write("\twhile(b<it.length)      \r\n");
      out.write("\t{\r\n");
      out.write("\t\tc = '0';\r\n");
      out.write("\t\twhile(c<letters.length)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(split[c] == chars[b])\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif(c == \"0\") { c = \"\"; }\r\n");
      out.write("\t\t\t\tif(eval(c+10) >= letters.length)\r\n");
      out.write("\t\t\t\t{num = eval(10-(letters.length-c));encrypted += split[num];}\r\n");
      out.write("\t\t\t\telse{num = eval(c+10);encrypted += split[num];}\r\n");
      out.write("\t\t\t}c++;\r\n");
      out.write("\t\t}b++;\r\n");
      out.write("\t}document.forms[0].data.value = encrypted;encrypted = '';\r\n");
      out.write("}\r\n");
      out.write("function decrypt(it)\r\n");
      out.write("{\r\n");
      out.write("\t var text_box = document.getElementById('target');\r\n");
      out.write("\t text_box.setAttribute('readonly', 'readonly'); \r\n");
      out.write("\t\r\n");
      out.write("\tvar b = '0';var chars = it.split(\"\");while(b<it.length){c = '0';while(c<letters.length){if(split[c] == chars[b]){if(c == \"0\") { c = \"\"; }if(eval(c-10) < 0){num = eval(letters.length-(10-c));encrypted += split[num];}else{num = eval(c-10);encrypted += split[num];}}c++;}b++;}document.forms[0].data.value = encrypted;encrypted = '';\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("// -->\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("<div style=\"height:20px;width:530px;position:absolute;top:125px;left:220px;border:2px solid #9D9D9D;padding:15;\">\r\n");
      out.write("<center>Encryption And Decryption</center>\r\n");
      out.write("</div> \r\n");
      out.write("<div style=\"height:170px;width:500px;position:absolute;top:170px;left:220px;border:2px solid #9D9D9D;padding:30;background-color:#9D9D9D\">\r\n");
      out.write("<FORM>\r\n");
      out.write("Enter Yout Text\r\n");
      out.write("<TEXTAREA ROWS=\"9\" COLS=\"60\" NAME=\"data\" id=\"target\" wrap=\"virtual\" ></TEXTAREA><BR>\r\n");
      out.write("<INPUT TYPE=\"BUTTON\" VALUE=\"Encrypt\" onClick=\"encrypt(document.forms[0].data.value)\">\r\n");
      out.write("<INPUT TYPE=\"BUTTON\" VALUE=\"Decrypt\" onClick=\"decrypt(document.forms[0].data.value)\">\r\n");
      out.write("</FORM>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
