/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2016-05-06 01:21:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.admin.comman.Global;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <title>Dynamic Cloud</title>\r\n");
      out.write("      \r\n");
      out.write("        \r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/CSS/style.css\" />\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/modernizr.custom.63321.js\"></script>\r\n");
      out.write("     \r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t\tbody {\r\n");
      out.write("\t\t\t\tbackground:  url(../images/3.jpg);\r\n");
      out.write("\t\t\t\tbackground-repeat: repeat-x;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t <div style=\"position:absolute;top:155px;left:335px;\">\r\n");
      out.write("        <div class=\"container\" >\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<div class=\"main\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t<form class=\"form-2\" action=\"");
      out.print(request.getContextPath());
      out.write("/AdminLogin\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<h1><span class=\"log-in\">Log in</span> or <span class=\"sign-up\">sign up</span></h1>\r\n");
      out.write("\t\t\t\t\t<p class=\"float\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"login\"><i class=\"icon-user\"></i>Username</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"username\" placeholder=\"Username or email\">\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<p class=\"float\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"password\"><i class=\"icon-lock\"></i>Password</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"password\" placeholder=\"Password\" class=\"showpassword\">\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<p class=\"clearfix\"> \r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" name=\"submit\" value=\"Login\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"reset\" class=\"log-twitter\" ></input>    \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(function(){\r\n");
      out.write("\t\t\t    $(\".showpassword\").each(function(index,input) {\r\n");
      out.write("\t\t\t        var $input = $(input);\r\n");
      out.write("\t\t\t        $(\"<p class='opt'/>\").append(\r\n");
      out.write("\t\t\t            $(\"<input type='checkbox' class='showpasswordcheckbox' id='showPassword' />\").click(function() {\r\n");
      out.write("\t\t\t                var change = $(this).is(\":checked\") ? \"text\" : \"password\";\r\n");
      out.write("\t\t\t                var rep = $(\"<input placeholder='Password' type='\" + change + \"' />\")\r\n");
      out.write("\t\t\t                    .attr(\"id\", $input.attr(\"id\"))\r\n");
      out.write("\t\t\t                    .attr(\"name\", $input.attr(\"name\"))\r\n");
      out.write("\t\t\t                    .attr('class', $input.attr('class'))\r\n");
      out.write("\t\t\t                    .val($input.val())\r\n");
      out.write("\t\t\t                    .insertBefore($input);\r\n");
      out.write("\t\t\t                $input.remove();\r\n");
      out.write("\t\t\t                $input = rep;\r\n");
      out.write("\t\t\t             })\r\n");
      out.write("\t\t\t        ).append($(\"<label for='showPassword'/>\").text(\"Show password\")).insertAfter($input.parent());\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\r\n");
      out.write("\t\t\t    $('#showPassword').click(function(){\r\n");
      out.write("\t\t\t\t\tif($(\"#showPassword\").is(\":checked\")) {\r\n");
      out.write("\t\t\t\t\t\t$('.icon-lock').addClass('icon-unlock');\r\n");
      out.write("\t\t\t\t\t\t$('.icon-unlock').removeClass('icon-lock');    \r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$('.icon-unlock').addClass('icon-lock');\r\n");
      out.write("\t\t\t\t\t\t$('.icon-lock').removeClass('icon-unlock');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<div style=\"position:absolute;top:145px;left:375px;color:red;\">\r\n");

if(request.getAttribute(Global.ADMIN_LOGIN_STATUS) != null)
{
	if(request.getAttribute(Global.ADMIN_LOGIN_STATUS).toString().equals(Global.ADMIN_INVALID_MESSAGE))
	{

      out.write("\r\n");
      out.write("\t<font color=\"red\" size=\"4\"><b>The username or password you entered is incorrect</b></font>\r\n");

	}
}

      out.write("\r\n");
      out.write("\r\n");

if(request.getAttribute(Global.IPADDRESS) != null)
{
	if(request.getAttribute(Global.IPADDRESS).toString().equals(Global.IPADDRESS_INVALID_MESSAGE))
	{

      out.write("\r\n");
      out.write("\t<font color=\"red\" size=\"4\"><b>Sorry,your IP Address is not Valid</b></font>\r\n");
	}
}

      out.write("\r\n");
      out.write("\r\n");

if(request.getAttribute(Global.USER_IPADDRESS) != null)
{
	if(request.getAttribute(Global.USER_IPADDRESS).toString().equals(Global.USER_IPADDRESS_INVALID_MESSAGE))
	{

      out.write("\r\n");
      out.write("\t<font color=\"red\" size=\"4\"><b>Sorry You are already using .....</b></font>\r\n");
	}
}

      out.write('	');
      out.write('\r');
      out.write('\n');

if(request.getAttribute(Global.USER_LOGIN_STATUS) != null)
{
	if(request.getAttribute(Global.USER_LOGIN_STATUS).toString().equals(Global.USER_INVALID_MESSAGE))
	{

      out.write("\r\n");
      out.write("\t<font color=\"red\" size=\"4\"><b>Server is too busy to handle your request</b></font>\r\n");
	}
}

      out.write("\r\n");
      out.write("</div>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
